### PR TITLE
Driver for MongoDB

### PR DESCRIPTION
**Pull request by dimag-jfrog**
Support for MongoDB driver by custom app-logic golang methods.

Users of the driver should pre-register their golang method receiver (struct) with methods in a fixed format - in a similiar fashion to how drivers are pre-registered before running Migrate(). 

MongoDB eval() operation is deprecated starting from MongoDB 3, so I couldn't use .json files and pass them to eval like .sql files are used for relational databases (as in Mongeez project), and using an embedded javascript interpreter sounds like an overkill, so golang methods were my preferred approach.

Gomethods migration files execution mechanism was added in a mongodb-agnostic manner - so that in future it could be extended for other purposes if needed.

### CODE REVIEW

**Comment by gravis** [comment]
@dimag-jfrog Could you add in our fork a `Versions` method to your driver, so it implements correctly the driver interface?
This repo is not maintained any more, so please use the PR https://github.com/gemnasium/migrate/pull/5 instead as base.

Thanks

**Comment by dimag-jfrog** [comment]
@gravis Sure, how do I do it? Should I fork from https://github.com/gemnasium/migrate/ and make a new pull request of those changes to MongoDB branch?

**Comment by mattes** [comment]
I rebased with master. Tests fail at:

```
--- FAIL: TestMigrate (0.41s)
        mongodb_test.go:59: Migration 'v0 -> v1: not exported method aborts migration': FAILED
                expected errors [Method v001_not_exported_method_up is not exported]
                but got [Non existing migrate method: v001_not_exported_method_up]
```

**Comment by dimag-jfrog** [comment]
OK, I will check/fix it in a few days.

**Comment by dimag-jfrog** [comment]
Merged master and fixed the errors.
Maybe I made a mistake and should have rebased instead?

**Comment by mattes** [comment]
Rebasing would be much appreciated. With 1,884 additions it's really hard for me to understand what changed and what not :-)

**Comment by dimag-jfrog** [comment]
No problem :-)

**Comment by dimag-jfrog** [comment]
This branch is a mess after the merge, I'll make a new pull request from a clean branch.

**Comment by dimag-jfrog** [comment]
Created a new branch with rebase (prepare_pr_2_rebase) and a new pull request  - Driver for Mongo DB (New).
Closing this pull request.

**Pull request closed without merging**
