### PR TITLE
MSSQL support

### PR DESCRIPTION
**Pull request by alaczi**
Uses the https://github.com/denisenkom/go-mssqldb driver
For tests https://hub.docker.com/r/microsoft/mssql-server-linux/ image added

### CODE REVIEW

**Comment by alaczi** [comment]
Seems builds are randomly failing with different reasons (sometimes something with gopkg, sometimes can't connect to the mssql container...

**Comment by alaczi** [comment]
@mattes will you consider signing up with a free appveyor account, travis legacy runners has only 3gigs of memory:
```
The build containers in our legacy build infrastructure have had 1.5 cores (with burst capacity) and 3GB of memory. 
```
And mssql image requires 3.25 by default.

On appveyor different mssql versions are available by default:

SQL Server 2008
SQL Server 2012
SQL Server 2014
SQL Server 2016

**Comment by mattes** [comment]
What is the legacy env? Looking at https://docs.travis-ci.com/user/ci-environment/ Looks like we have 7.5GB of memory for each build.

Thanks for opening this PR and adding support for SQL server! Any particular interest in porting this to the latest version v3? :-)

**Comment by alaczi** [comment]
Ah. I probably read an old article, when they introduced the containerised build machines.
Then I have no idea, it seems randomly fails on different versions of go with unable to connect to the mssql ip. I can work on the v3.0 port, but first we have to sort out this build issue.

**Comment by mattes** [comment]
I see the following error:

> mssql_test.go:38: Unable to open tcp connection with host '172.17.0.6:1433': dial tcp 172.17.0.6:1433: connection refused

I assume this is what happens:

1. Containers are being started
1. MSSQL tests are run BUT container is not ready, yet

v3 doesn't use docker-compose anymore to "fix" this.

**Comment by mattes** [comment]
Would you mind changing the target branch to [v1](https://github.com/mattes/migrate/tree/v1) ?

**Comment by alaczi** [comment]
@mattes Changed the target branch to v1

**Comment by alaczi** [comment]
@mattes I did some workaround to allow mssql to boot up. (maximum of two minutes). This made the build pass nicely except with go 1.4.

```
# github.com/cznic/ql
../../cznic/ql/parser.go:861: syntax error: unexpected :, expecting }
../../cznic/ql/parser.go:1681: non-declaration statement outside function body
../../cznic/ql/parser.go:1682: syntax error: unexpected )
```
This package declares map without explicit element type declaration what was introduced in go 1.5:
https://golang.org/doc/go1.5

Any thoughts?

**Comment by mattes** [comment]
How do you feel about removing Go 1.4 support?

**Comment by alaczi** [comment]
I think it's safe to drop support of 1.4, upgrading to newer go versions are quite straightforward, never had issue to do it.

**Comment by mattes** [comment]
Awesome! Thanks for your work!

**Pull request merged**
