### PR TITLE
source/aws-s3: implement the driver

### LINKED ISSUE #162: Implement AWS S3 source driver

### PR DESCRIPTION
**Pull request by fsouza**
Similar to #227. Closes #162.

### CODE REVIEW

**Comment by mattes** [comment]
awesome! thank you so much for your work! same question around loadMigrations (https://github.com/mattes/migrate/pull/228/files#diff-edec97eacd6ee15de2eaffbbb87f4e2dR51). Does the AWS API allow to find a file without loading them all upfront?

**Comment by fsouza** [comment]
@mattes with S3 we can control the pagination by setting the page number to 1, so this could work.

Do you think it's worth to do that? Is it common to load only one or two migrations? Right now, loadMigrations only lists the files inside the "folder", the contents of the files only get downloaded when ReadUp and ReadDown are called, similar to the file source driver.

I'm not very familiar with the way migrate loads and run migrations, so apologies if this is obvious x)

**Comment by mattes** [comment]
Let's merge it the way it is for now. We can always iterate from here. 

I believe loading the full "directory tree" is somewhat expensive especially if there are hundreds of migrations.

**Comment by mattes** [comment]
thanks for your hard work!

**Comment by fsouza** [comment]
@mattes I can work on that as well! Do you want me to try to get this working (loading 1 by 1, or even n by n where n is configurable?)?

**Comment by mattes** [comment]
If you have time, yeah that would be awesome! 

The idea is that all the funcs from the Source driver ([First/Prev/Next/ReadUp/ReadDown](https://github.com/mattes/migrate/blob/master/source/driver.go#L45-L72)) make as few API calls as possible with only the data returned that's really required.

Imagine someone would use the migrate CLI. It's impossible to cache the directory tree. So for each `migrate up` you end up reading all migrations first, just to go from one migration to another. 

When used as package, it's a different story. Caching of the directory tree is possible, but what happens if the directory tree changes in between migrations...

Does that make sense?

**Comment by fsouza** [comment]
@mattes makes sense! I'll work on that at some point in this week.

I'll also try to think about some solution for a similar behavior on GCS.

**Pull request merged**
