### PR TITLE
TravisCI Updates

### PR DESCRIPTION
**Pull request by rmulley**
This updates the `.travis.yml` config to:
- Use the latest patch versions of each minor golang version, [per TravisCI docs](https://docs.travis-ci.com/user/languages/go/#Specifying-a-Go-version-to-use)
- Add go 1.8.x to the test matrix
- Pull the latest docker-compose version, 1.11.2

### CODE REVIEW

**Comment by mattes** [comment]
failing at https://travis-ci.org/mattes/migrate/jobs/221851407#L443. any idea?

**Comment by rmulley** [comment]
Not sure....strange that it only failed on `go 1.4.3`. I'll take a deeper look into the `cznic/ql` library and see if there is a problem there.

**Comment by mattes** [comment]
Would you mind changing the target branch to [v1](https://github.com/mattes/migrate/tree/v1) ?

**Comment by mattes** [comment]
just merged

**Pull request merged**
