### PR TITLE
adapted the sqlite driver for v3 (#165)

### PR DESCRIPTION
**Pull request by maxvw**
When I discovered your project I thought it was perfect, just what I needed! However soon after that I discovered the latest version lacked SQLite support. So I've copied the Ql driver and adapted it to work for SQLite, I think I've covered everything but if I forgot something please let me know!

I wasn't sure which naming convention to use, in the previous version I see it was called `sqlite3` but in the new version there was a directory reserved called `sqlite`. I've opted for the `sqlite3` naming as the actual driver is also called `sqlite3` so I think that made more sense.

### CODE REVIEW

**Comment by bt** [comment]
Hey @mattes, I desperately need this functionality. Could you please merge this PR in?

Thank you! 😄

**Comment by mattes** [comment]
can you add the build file (ex https://github.com/mattes/migrate/blob/master/cli/build_ql.go) for this driver, please? 

thanks for the PR! will merge after this!

**Comment by maxvw** [comment]
@mattes done, that should work now too.

(I had completely overlooked it as I only use the functionality in Go itself, not the command-line version)

**Comment by mattes** [comment]
merged! thank you so much!

**Comment by mattes** [comment]
@maxvw I see some errors: https://travis-ci.org/mattes/migrate/jobs/239468284#L1513 Any idea what's going on?

**Comment by maxvw** [comment]
@mattes on first inspection this seems to be due to the fact that `go-sqlite3` is a `cgo` package, I'm still relatively new to Go and didn't know this was a thing / wasn't aware of the impact that has when it comes to cross-compiling. I'm not sure what the fix would be to make this work right now, from initial reading it sounds like you need to set the correct `CC` env for each `GOOS` and also set  `CGO_ENABLED=1`. 

Someone mentioning a similar issue: https://github.com/mattn/go-sqlite3/issues/384

But if it makes cross-compiling more challenging people will also have this issue in their own project if they include the `migrate` library, right? So the question is if that's desired or not. I have not found a better sqlite3 go package unfortunately (this is also the same one you originally used in v1)

**Comment by mattes** [comment]
ok, thanks! I just enabled CGO based on: https://github.com/mattn/go-sqlite3/commit/98981b4a3bc61c9f76cd54c691f1262041973c3e

**Comment by maxvw** [comment]
@mattes alright nice, hopefully that solves it!

**Pull request merged**
