### PR TITLE
Allow user to programatically pass database object via sqlite driver

### PR DESCRIPTION
**Pull request by baconz**
Meant to be used with :memory: type databases

Addresses #71

This is a rough stab at an approach to this. Let me know if you had something else in mind

### CODE REVIEW

**Comment by gravis** [comment]
I think that's the biggest concern about migrate. The DB connection should be the responsibility of the user. We're seeing more and more hacks like this to avoid the origin problem.

**Comment by baconz** [comment]
@gravis would you be willing to merge this (or something like it) into your fork? I think it is a step in the right direction.

**Comment by mattes** [comment]
I like the idea to pass in an existing instance connection.

**Comment by mattes** [comment]
https://github.com/mattes/migrate/blob/v3.0-prev/migrate.go#L76

```
func NewWithDatabaseInstance(sourceUrl string, databaseName string, databaseInstance database.Driver) (*Migrate, error) {
```

**Pull request closed without merging**
