### PR TITLE
add support for custom delimiter in mysql migrations

### PR DESCRIPTION
**Pull request by phemmer**
This implements a solution for #38 

It basically adds support for the migration file including `delimiter foo` in the first line, and using `foo` as the delimiter for multiple statements.

Yes, this is a hack, but it solves the issue, and doesn't introduce new syntax (`delimiter foo` is valid for mysql CLI)

### CODE REVIEW

**Comment by mattes** [comment]
Thanks for your PR. Not sure if I got it right. ``DELIMITER`` just changes the ``;`` symbol to something else. Could you give an example how that would work with multiple statements?

**Comment by phemmer** [comment]
This is one of our migrations which is using it:

```
delimiter "\n--\n"

CREATE TABLE session_event (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	type ENUM('insert','update') NOT NULL,
	session_id BIGINT UNSIGNED NOT NULL
) engine=InnoDB

--

CREATE TRIGGER session_insert AFTER INSERT ON session
FOR EACH ROW
BEGIN
	INSERT INTO session_event SET type='insert', session_id=NEW.id;
	SET @event_id = LAST_INSERT_ID();
	SET @event_id_min = GREATEST(@event_id, 1000) - 1000;
	DELETE FROM session_event WHERE id < @event_id_min;
END

--

CREATE TRIGGER sesion_update AFTER UPDATE ON session
FOR EACH ROW
BEGIN
	INSERT INTO session_event SET type='update', session_id=NEW.id;
	SET @event_id = LAST_INSERT_ID();
	SET @event_id_min = GREATEST(@event_id, 1000) - 1000;
	DELETE FROM session_event WHERE id < @event_id_min;
END
```

**Comment by mattes** [comment]
I see. How about implementing https://github.com/ziutek/mymysql#example-4---multi-statement--multi-result ?

**Comment by phemmer** [comment]
I don't see how that is relevant. The issue isn't executing multiple statements, the issue is executing statements with a semicolon in them.

**Comment by mattes** [comment]
I think by implementing ziutek/mymysql we don't need any workarounds for delimiters.

**Comment by phemmer** [comment]
I don't think it'll have any bearing on the issue. The package might have better support for multiple SQL statements, but I still see no way to change the delimiter.

**Comment by phemmer** [comment]
Closing this since it seems to have gone stale. We've also switched to another migration tool which among other things, has support for custom statement delimiters.

**Pull request closed without merging**
