### PR TITLE
Add driver to firebird

### PR DESCRIPTION
**Pull request by vyper**
- [x] Driver implementation
- [x] README
- [x] configure Dockerfile & docker-compose.yml

### CODE REVIEW

**Comment by mattes** [comment]
@vyper this is great! would you potentially interested in porting that to version 3?

**Comment by vyper** [comment]
We have a [problem](https://github.com/nakagami/firebirdsql#requirements). ):

**Comment by mattes** [comment]
```
github.com/nakagami/firebirdsql (download)
package context: unrecognized import path "context" (import path does not begin with hostname)
```

I think this might be the issue?

**Comment by vyper** [comment]
Yehp, the `context` package has been added in Go 1.7 ):

**Comment by mattes** [comment]
If Go >=1.7 is a hard requirement I think it makes sense to just implement firebirdsql support with the latest migrate version 3.

**Comment by mattes** [comment]
Would you mind changing the target branch to [v1](https://github.com/mattes/migrate/tree/v1) ?

**Pull request closed without merging**
